#!/usr/bin/env python3
"""Regenerate the "read against" pin table in resources/codebases.md.

Why this exists
---------------
The reading guides quote `file:line` anchors into real codebases — a few
thousand of them. An anchor is only meaningful next to the commit it was read
at, because line numbers move. CONTRIBUTING asks for that commit to be
recorded; recording it in each of the 230 guides would mean thousands of SHAs
drifting independently, so it is recorded once, here, for every clone the
guides reference.

Usage
-----
    python3 tools/pin-table.py            # rewrite the table in place
    python3 tools/pin-table.py --check    # exit 1 if the table is stale

It reads the clones under ~/repos (override with DLP_CLONES) and only emits a
row for a repo it can actually verify: a real git checkout, with a resolvable
HEAD and an origin URL. Repos it cannot verify are reported and left out
rather than guessed at.
"""

import os
import re
import subprocess
import sys
from pathlib import Path

CLONES = Path(os.environ.get("DLP_CLONES", Path.home() / "repos"))
REPO = Path(__file__).resolve().parent.parent
TARGET = REPO / "resources" / "codebases.md"
START = "<!-- BEGIN PIN TABLE (generated by tools/pin-table.py) -->"
END = "<!-- END PIN TABLE -->"

# Words that collide with ordinary prose or with directories that are not
# reference clones, so a mention count means nothing for them.
IGNORE = {"database-learning-path", "tensor", "benchmark", "llm-model"}
MIN_MENTIONS = 2


def git(repo: Path, *args: str) -> str:
    r = subprocess.run(
        ["git", "-C", str(repo), *args], capture_output=True, text=True
    )
    return r.stdout.strip() if r.returncode == 0 else ""


def corpus() -> str:
    """Everything the mention count is computed over.

    The generated table is stripped out first: it names every repo it lists, so
    counting it would make each run's numbers depend on the previous run's
    output and `--check` would never settle.
    """
    text = []
    for pat in ("topics/*/*.md", "resources/*.md", "capstone/*.md"):
        for f in REPO.glob(pat):
            s = f.read_text(encoding="utf8")
            s = re.sub(
                re.escape(START) + r".*?" + re.escape(END), "", s, flags=re.S
            )
            text.append(s)
    return "\n".join(text)


def main() -> int:
    check = "--check" in sys.argv
    if not CLONES.is_dir():
        print(f"no clone directory at {CLONES} — set DLP_CLONES", file=sys.stderr)
        return 2

    blob = corpus()
    rows, unverified = [], []
    for d in sorted(os.listdir(CLONES)):
        if d in IGNORE or not (CLONES / d / ".git").exists():
            continue
        mentions = len(re.findall(rf"(?<![\w/-]){re.escape(d)}(?![\w-])", blob, re.I))
        if mentions < MIN_MENTIONS:
            continue
        sha = git(CLONES / d, "rev-parse", "--short", "HEAD")
        date = git(CLONES / d, "log", "-1", "--format=%cs")
        url = git(CLONES / d, "remote", "get-url", "origin")
        if not (sha and date and url):
            unverified.append(d)
            continue
        url = re.sub(r"\.git$", "", url)
        rows.append((d, mentions, sha, date, url))

    rows.sort(key=lambda r: (-r[1], r[0].lower()))

    lines = [
        START,
        "",
        "| clone | read at | dated | mentions | origin |",
        "|---|---|---|---|---|",
    ]
    for name, mentions, sha, date, url in rows:
        lines.append(f"| `{name}` | `{sha}` | {date} | {mentions} | [{url}]({url}) |")
    lines += ["", END]
    table = "\n".join(lines)

    current = TARGET.read_text(encoding="utf8")
    if START in current and END in current:
        updated = re.sub(
            re.escape(START) + r".*?" + re.escape(END), table, current, flags=re.S
        )
    else:
        updated = current.rstrip() + "\n\n" + table + "\n"

    if check:
        if updated != current:
            print("pin table is stale — run python3 tools/pin-table.py")
            return 1
        print("pin table is current")
        return 0

    TARGET.write_text(updated, encoding="utf8")
    print(f"wrote {len(rows)} pinned clones to {TARGET.relative_to(REPO)}")
    if unverified:
        print("could not verify (left out):", ", ".join(unverified))
    return 0


if __name__ == "__main__":
    sys.exit(main())
